--
-- SP_CUSTOMER_MODELS_UPDATE  (Procedure) 
--
CREATE OR REPLACE PROCEDURE DWH_CAMPAIGN_USER01.SP_CUSTOMER_MODELS_UPDATE IS
    VDATE_KEY               VARCHAR2(4);
    --VDATE DATE := TO_DATE(TO_DATE(P_PROCESS_DATE,'YYYYMMDD'),'DD/MM/RRRR');
BEGIN
    SELECT DATE_KEY INTO VDATE_KEY 
    FROM DATE_DIM
    WHERE DATE_KEY = (SELECT DATE_KEY FROM DATE_DIM WHERE TRUNC(DATE_VALUE) = TRUNC(SYSDATE-1));
    
       --------CLV-------    
    MERGE INTO CUSTOMER_MODELS A
    USING (SELECT MSISDN,CLV 
    FROM LD_CLV_LD  
    WHERE DATE_KEY=VDATE_KEY
    ) V 
    ON (A.MSISDN = V.MSISDN AND TRUNC(SNAPSHOT_DATE)=TRUNC(SYSDATE-1))
    WHEN MATCHED THEN
    UPDATE SET A.LD_CLV=V.CLV;
    COMMIT;
    
           --------CROSSSELL-------    
    MERGE INTO CUSTOMER_MODELS A
    USING (SELECT MSISDN,PREFERRED 
    FROM LD_CROSSSELL_LD  
    WHERE DATE_KEY=VDATE_KEY
    ) V 
    ON (A.MSISDN = V.MSISDN AND TRUNC(SNAPSHOT_DATE)=TRUNC(SYSDATE-1))
    WHEN MATCHED THEN
    UPDATE SET A.LD_CROSSSELL=V.PREFERRED;
    COMMIT;
    
           --------UPSELL-------    
    MERGE INTO CUSTOMER_MODELS A
    USING (SELECT MSISDN,PREFERRED 
    FROM LD_UPSELL_LD  
    WHERE DATE_KEY=VDATE_KEY
    ) V 
    ON (A.MSISDN = V.MSISDN AND TRUNC(SNAPSHOT_DATE)=TRUNC(SYSDATE-1))
    WHEN MATCHED THEN
    UPDATE SET A.LD_UPSELL=V.PREFERRED;
    COMMIT;
    
           --------PROFIT_SEGMENTATION-------    
    MERGE INTO CUSTOMER_MODELS A
    USING (SELECT MSISDN,NORMAL_VAL 
    FROM LD_PROFIT_SEGMENTATION  
    WHERE DATE_KEY=VDATE_KEY
    ) V 
    ON (A.MSISDN = V.MSISDN AND TRUNC(SNAPSHOT_DATE)=TRUNC(SYSDATE-1))
    WHEN MATCHED THEN
    UPDATE SET A.LD_PROFIT_SEGMENTATION=V.NORMAL_VAL;
    COMMIT;
    
               --------USEGS_SEGMENTATION -------    
    MERGE INTO CUSTOMER_MODELS A
    USING (SELECT MSISDN,USEGS_SEGMENTATION 
    FROM LD_USEGS_SEGMENTATION  
    WHERE DATE_KEY=VDATE_KEY
    ) V 
    ON (A.MSISDN = V.MSISDN AND TRUNC(SNAPSHOT_DATE)=TRUNC(SYSDATE-1))
    WHEN MATCHED THEN
    UPDATE SET A.LD_USEGS_SEGMENTATION=V.USEGS_SEGMENTATION;
    COMMIT;
    
    
    
END;
/

