--
-- SP_LD_CLV_LD_OLD_SHAHIN  (Procedure) 
--
CREATE OR REPLACE PROCEDURE DWH_CAMPAIGN_USER01.SP_LD_CLV_LD_OLD_SHAHIN IS
MIN_VREVENUE NUMBER;
MAX_VREVENUE NUMBER;
MIN_DREVENUE NUMBER;
MAX_DREVENUE NUMBER;
MIN_REVENUE  NUMBER;
MAX_REVENUE  NUMBER;
VDATE_KEY    VARCHAR2(4);

BEGIN

SELECT DATE_KEY INTO VDATE_KEY
FROM DATE_DIM WHERE TRUNC(DATE_VALUE)=TRUNC(SYSDATE-1);
---------------------------------------------
SELECT MIN(VOICE_REVENUE) INTO MIN_VREVENUE
FROM CLM_VOICE_REV@CAMPAING_TO_DWH05
WHERE DATE_KEY = VDATE_KEY;

SELECT MAX(VOICE_REVENUE) INTO MAX_VREVENUE
FROM CLM_VOICE_REV@CAMPAING_TO_DWH05
WHERE DATE_KEY = VDATE_KEY;

SELECT MIN(DATA_REVENUE) INTO MIN_DREVENUE
FROM CLM_DATA_REV@CAMPAING_TO_DWH05
WHERE DATE_KEY = VDATE_KEY;

SELECT MAX(DATA_REVENUE) INTO MAX_DREVENUE
FROM CLM_DATA_REV@CAMPAING_TO_DWH05
WHERE DATE_KEY = VDATE_KEY;

MIN_REVENUE := NVL(MIN_VREVENUE,0)+NVL(MIN_DREVENUE,0);

MAX_REVENUE:= NVL(MAX_VREVENUE,0)+NVL(MAX_DREVENUE,0);
--------------------------------------------

INSERT INTO LD_CLV_LD(MSISDN, CLV, DATE_KEY)

SELECT MSISDN, TO_CHAR(CLV,'9999.99') CLV,VDATE_KEY
FROM
(
SELECT MSISDN,(TOTAL_VREVENUE-NVL(MIN_REVENUE,0))/(NVL(MAX_REVENUE,0)-NVL(MIN_REVENUE,0)) AS CLV
FROM
(
SELECT a.MSISDN,NVL(VOICE_REVENUE,0)+NVL(DATA_REVENUE,0) AS TOTAL_VREVENUE
FROM
(SELECT MSISDN,SUM(VOICE_REVENUE) AS VOICE_REVENUE
FROM CLM_VOICE_REV@CAMPAING_TO_DWH05
WHERE DATE_KEY=VDATE_KEY
group by MSISDN) A 
FULL OUTER JOIN 
(SELECT MSISDN,SUM(DATA_REVENUE)AS DATA_REVENUE
FROM CLM_DATA_REV@CAMPAING_TO_DWH05
WHERE DATE_KEY=VDATE_KEY
group by MSISDN)B
ON(A.MSISDN=B.MSISDN)
)
WHERE MSISDN IS NOT NULL
);

COMMIT;
END;
/

