--
-- SP_LD_LD_UPSELL_LD_OLD  (Procedure) 
--
CREATE OR REPLACE PROCEDURE DWH_CAMPAIGN_USER01.SP_LD_LD_UPSELL_LD_OLD IS
VDATE_KEY VARCHAR2(4);
BEGIN

SELECT DATE_KEY INTO VDATE_KEY
FROM DATE_DIM WHERE TRUNC(DATE_VALUE)=TRUNC(SYSDATE-1);


INSERT INTO LD_UPSELL_LD
SELECT MSISDN, PREFERRED,VDATE_KEY
FROM
(SELECT MSISDN,VOICE,SMS,DATA,
CASE
WHEN NVL(VOICE,0) < NVL(SMS,0) AND NVL(VOICE,0) < NVL(DATA,0) 
THEN 1
WHEN NVL(SMS,0) < NVL(VOICE,0) AND NVL(SMS,0) < NVL(DATA,0) 
THEN 2
WHEN NVL(DATA,0) < NVL(VOICE,0) AND NVL(DATA,0) < NVL(SMS,0) 
THEN 3

END PREFERRED

FROM 
(SELECT MSISDN, VOICE, SMS, DATA
FROM
(SELECT A.MSISDN,A.VOICE_REVENUE VOICE,B.SMS_REVENUE SMS, C.DATA_REVENUE DATA
from
(select MSISDN,sum(VOICE_REVENUE)as VOICE_REVENUE
FROM CLM_VOICE_REV@CAMPAING_TO_DWH05
where DATE_KEY=VDATE_KEY
group by msisdn)A,
(select msisdn,sum(SMS_REVENUE)as SMS_REVENUE
from CLM_SMS_REV@CAMPAING_TO_DWH05 
where DATE_KEY=VDATE_KEY
group by msisdn)B,
(select msisdn,sum(DATA_REVENUE)as DATA_REVENUE
from CLM_DATA_REV@CAMPAING_TO_DWH05 
where DATE_KEY=VDATE_KEY
group by msisdn) C
WHERE A.MSISDN=B.MSISDN
AND A.MSISDN=C.MSISDN
)
WHERE VOICE > 0
AND  SMS > 0
AND DATA > 0)
);
COMMIT;
END;
/

