--
-- SP_LD_USEGS_SEGMENTATION_MANUAL  (Procedure) 
--
CREATE OR REPLACE PROCEDURE DWH_CAMPAIGN_USER01.SP_LD_USEGS_SEGMENTATION_MANUAL (P_DATE VARCHAR2)  IS
MIN_VUSEGS NUMBER;
MAX_VUSEGS NUMBER;
MIN_DUSEGS NUMBER;
MAX_DUSEGS NUMBER;

MIN_USEGS NUMBER;
MAX_USEGS NUMBER;

VDATE_KEY VARCHAR2(4);

BEGIN

SELECT DATE_KEY INTO VDATE_KEY
FROM DATE_DIM WHERE TRUNC(DATE_VALUE)=TRUNC(TO_DATE(P_DATE,'RRRRMMDD'));
---------------------------------------------
SELECT MIN(NORMAL_VAL) INTO MIN_VUSEGS
FROM CLM_VOICE_USEGS@CAMPAING_TO_DWH05
WHERE DATE_KEY = VDATE_KEY;

SELECT MAX(NORMAL_VAL) INTO MAX_VUSEGS
FROM CLM_VOICE_USEGS@CAMPAING_TO_DWH05
WHERE DATE_KEY = VDATE_KEY;

SELECT MIN(NORMAL_VAL) INTO MIN_DUSEGS
FROM CLM_DATA_USEGS@CAMPAING_TO_DWH05
WHERE DATE_KEY = VDATE_KEY;

SELECT MAX(NORMAL_VAL) INTO MAX_DUSEGS
FROM CLM_DATA_USEGS@CAMPAING_TO_DWH05
WHERE DATE_KEY = VDATE_KEY;

MIN_USEGS := NVL(MIN_VUSEGS,0)+NVL(MIN_DUSEGS,0);

MAX_USEGS:= NVL(MAX_VUSEGS,0)+NVL(MAX_DUSEGS,0);


--??_????????????????????=(??-??_??????)/(??_??????-??_?????? )
--------------------------------------------
INSERT INTO LD_USEGS_SEGMENTATION(MSISDN, USEGS_SEGMENTATION, DATE_KEY)

SELECT MSISDN, TO_CHAR(USEGS_SEGMENTATION,'9999.99') USEGS_SEGMENTATION,VDATE_KEY
FROM
(
SELECT MSISDN,(nvl(TOTAL_USEGS,0)-NVL(MIN_USEGS,0))/(NVL(MAX_USEGS,0)-NVL(MIN_USEGS,0)) AS USEGS_SEGMENTATION
FROM
(SELECT S.MSISDN,SUM(NORMAL_VAL) AS TOTAL_USEGS
  FROM  
        (
        SELECT A.MSISDN,A.NORMAL_VAL
        FROM CLM_VOICE_USEGS@CAMPAING_TO_DWH05 A
        WHERE A.DATE_KEY=VDATE_KEY
        UNION ALL
        SELECT B.MSISDN,B.NORMAL_VAL
        FROM CLM_DATA_USEGS@CAMPAING_TO_DWH05 B
        WHERE B.DATE_KEY=VDATE_KEY
        )S
        GROUP BY S.MSISDN
        )SS
WHERE MSISDN IS NOT NULL
);
commit;


END;
/

