--
-- P_CLM_DATA_USEGS  (Procedure) 
--
CREATE OR REPLACE PROCEDURE DWH_USER.P_CLM_DATA_USEGS (P_START_DATE VARCHAR2) IS
VDATE_KEY VARCHAR2(4);
MIN_DUSEGS NUMBER;
MAX_DUSEGS NUMBER;

BEGIN

SELECT DATE_KEY INTO VDATE_KEY 
FROM DATE_DIM
WHERE DATE_KEY = (SELECT DATE_KEY FROM DATE_DIM WHERE TO_CHAR(DATE_VALUE,'RRRRMMDD')=P_START_DATE); 


INSERT INTO CLM_DATA_USEGS(DATE_KEY, MSISDN, DATA_USEGS_MB)
SELECT /* + PARALLEL(A,16)*/ VDATE_KEY,A.MSISDN,TO_NUMBER(TO_CHAR(SUM(A.G384_TOTALFLUX),'999999.99')) AS G384_TOTALFLUX 
FROM
    (
    SELECT /* + PARALLEL(A,16)*/ G372_CALLINGPARTYNUMBER AS MSISDN,G384_TOTALFLUX/1024/1024 AS G384_TOTALFLUX
    FROM L3_DATA A
    WHERE G383_CHARGINGTIME_KEY = VDATE_KEY
    ) A
GROUP BY A.MSISDN;
COMMIT;

    BEGIN

        SELECT MIN(DATA_USEGS_MB) INTO MIN_DUSEGS
        FROM CLM_DATA_USEGS
        WHERE DATE_KEY = VDATE_KEY;

        SELECT MAX(DATA_USEGS_MB) INTO MAX_DUSEGS
        FROM CLM_DATA_USEGS
        WHERE DATE_KEY = VDATE_KEY;



        MERGE INTO CLM_DATA_USEGS A
        USING (SELECT MSISDN,(NVL(DATA_USEGS_MB,0)-NVL(MIN_DUSEGS,0))/(NVL(MAX_DUSEGS,0)-NVL(MIN_DUSEGS,0)) AS NDATA_USEGS
                FROM CLM_DATA_USEGS
                WHERE DATE_KEY = VDATE_KEY) V 
        ON (A.MSISDN = V.MSISDN) 
        WHEN MATCHED THEN
        UPDATE SET A.NORMAL_VAL=V.NDATA_USEGS;
        COMMIT;
    END;

END;
/

