--
-- P_CLM_VOICE_REV  (Procedure) 
--
CREATE OR REPLACE PROCEDURE DWH_USER.P_CLM_VOICE_REV (P_START_DATE VARCHAR2) IS

BEGIN


INSERT INTO CLM_VOICE_REV(DATE_KEY, MSISDN,BPARTY, VOICE_REVENUE, DURATION)
SELECT /* + PARALLEL(A,16)*/ (SELECT DATE_KEY FROM DATE_DIM WHERE TO_CHAR(DATE_VALUE,'RRRRMMDD')=P_START_DATE) DATE_KEY,A.MSISDN,BPARTY,SUM(A.DEBIT_AMOUNT),SUM(DURATION)/60
FROM
    (
    SELECT /* + PARALLEL(A,16)*/  V372_CALLINGPARTYNUMBER AS MSISDN,V373_CALLEDPARTYNUMBER BPARTY,V41_DEBIT_AMOUNT AS DEBIT_AMOUNT,(V35_RATE_USAGE-V50_PAY_FREE_UNIT_DURATION) AS DURATION
    FROM L3_VOICE A
    WHERE V387_CHARGINGTIME_KEY=(SELECT DATE_KEY FROM DATE_DIM WHERE TO_CHAR(DATE_VALUE,'RRRRMMDD')=P_START_DATE) 
    AND V378_SERVICEFLOW=1
    UNION ALL
    SELECT /*+PARALLEL(P,15)*/ R375_CHARGINGPARTYNUMBER AS MSISDN,null as BPARTY,R41_DEBIT_AMOUNT AS DEBIT_AMOUNT,NULL AS DURATION
    FROM L3_RECURRING P
    WHERE R377_CYCLEBEGINTIME_KEY =(SELECT DATE_KEY FROM DATE_DIM WHERE TO_CHAR(DATE_VALUE,'RRRRMMDD')=P_START_DATE)
    AND R385_OFFERINGID IN ( SELECT OFFERING_ID FROM OFFER_DIM WHERE OFFER_TYPE='Voice')
    ) A
GROUP BY A.MSISDN,BPARTY;
COMMIT;

END;
/

