--
-- P_CLM_VOICE_USEGS  (Procedure) 
--
CREATE OR REPLACE PROCEDURE DWH_USER.P_CLM_VOICE_USEGS (P_START_DATE VARCHAR2) IS
MIN_VUSEGS NUMBER;
MAX_VUSEGS NUMBER;
VDATE_KEY VARCHAR2(4);
BEGIN

SELECT DATE_KEY INTO VDATE_KEY 
FROM DATE_DIM
WHERE DATE_KEY = (SELECT DATE_KEY FROM DATE_DIM WHERE TO_CHAR(DATE_VALUE,'RRRRMMDD')=P_START_DATE);

INSERT INTO CLM_VOICE_USEGS(DATE_KEY, MSISDN, VOICE_USEGS_MIN)
SELECT /* + PARALLEL(A,16)*/  VDATE_KEY,A.MSISDN,TO_NUMBER(TO_CHAR(SUM(A.V35_RATE_USAGE),'999999.99')) AS V35_RATE_USAGE 
FROM
    (
    SELECT /* + PARALLEL(A,16)*/  V372_CALLINGPARTYNUMBER AS MSISDN,V35_RATE_USAGE/60 AS V35_RATE_USAGE
    FROM L3_VOICE A
    WHERE V387_CHARGINGTIME_KEY=VDATE_KEY
    AND V378_SERVICEFLOW=1
    ) A
GROUP BY A.MSISDN;
COMMIT;

------------------------------------------
    BEGIN 
        
        SELECT MIN(VOICE_USEGS_MIN) INTO MIN_VUSEGS
        FROM CLM_VOICE_USEGS
        WHERE DATE_KEY = VDATE_KEY;

        SELECT MAX(VOICE_USEGS_MIN) INTO MAX_VUSEGS
        FROM CLM_VOICE_USEGS
        WHERE DATE_KEY = VDATE_KEY;

        MERGE INTO CLM_VOICE_USEGS A
        USING (SELECT MSISDN,(NVL(VOICE_USEGS_MIN,0)-NVL(MIN_VUSEGS,0))/(NVL(MAX_VUSEGS,0)-NVL(MIN_VUSEGS,0)) AS NVOICE_USEGS
                FROM CLM_VOICE_USEGS
                WHERE DATE_KEY = VDATE_KEY) V 
        ON (A.MSISDN = V.MSISDN) 
        WHEN MATCHED THEN
        UPDATE SET A.NORMAL_VAL=V.NVOICE_USEGS;
        COMMIT;
END;

END;
/

