--
-- P_CROSS_SELL_LD_MANUAL  (Procedure) 
--
CREATE OR REPLACE PROCEDURE DWH_USER.P_CROSS_SELL_LD_MANUAL (P_DATE VARCHAR2) IS
    VDATE_KEY       VARCHAR2(4);
BEGIN

SELECT DATE_KEY INTO VDATE_KEY
FROM DATE_DIM WHERE TRUNC(DATE_VALUE) = TRUNC(TO_DATE(P_DATE,'RRRRMMDD'));



  --EXECUTE IMMEDIATE  'TRUNCATE TABLE PKPI DROP STORAGE';
  --EXECUTE IMMEDIATE 'ALTER TABLE PKPI TRUNCATE PARTITION PKPI_||VDATE_KEY DROP STORAGE';
    
DELETE CROSS_SELL_LD WHERE DATE_KEY=VDATE_KEY;
COMMIT;
    
INSERT INTO CROSS_SELL_LD
SELECT A.MSISDN,COALESCE (VOICE_PPU_REVENUE,0)+COALESCE (RECURRING_VOICE_REVENUE,0) VOICE_REVENUE, 
       COALESCE (DATA_PPU_REVENUE,0)+COALESCE (RECURRING_DATA_REVENUE,0) DATA_REVENUE,
       COALESCE (SMS_PPU_REVENUE,0)+COALESCE (RECURRING_SMS_REVENUE,0) SMS_REVENUE,
       COALESCE (RECURRING_COMBO_REVENUE,0) COMBO_REVENUE,COALESCE (RECHARGE_AMOUNT,0)RECHARGE_AMOUNT,VDATE_KEY

FROM
(SELECT /*+PARALLEL(P,15)*/ MSISDN
FROM LAST_ACTIVITY_FCT_LD P
WHERE LU_DATE_KEY  =VDATE_KEY
GROUP BY MSISDN
)A
LEFT OUTER JOIN
(SELECT /*+PARALLEL(P,15)*/ V372_CALLINGPARTYNUMBER,SUM (V41_DEBIT_AMOUNT) VOICE_PPU_REVENUE 
FROM 
 L3_VOICE  P
WHERE V387_CHARGINGTIME_KEY  = VDATE_KEY
AND V378_SERVICEFLOW=1
GROUP BY V372_CALLINGPARTYNUMBER
)B ON A.MSISDN=B.V372_CALLINGPARTYNUMBER
LEFT OUTER JOIN
(SELECT /*+PARALLEL(P,15)*/ G372_CALLINGPARTYNUMBER,SUM (G41_DEBIT_AMOUNT) DATA_PPU_REVENUE 
FROM L3_DATA  P
WHERE G383_CHARGINGTIME_KEY  = VDATE_KEY
GROUP BY G372_CALLINGPARTYNUMBER
)C ON A.MSISDN=C.G372_CALLINGPARTYNUMBER
LEFT OUTER JOIN
(SELECT /*+PARALLEL(P,15)*/ S372_CALLINGPARTYNUMBER,SUM (S41_DEBIT_AMOUNT) SMS_PPU_REVENUE 
FROM  L3_SMS P
WHERE S387_CHARGINGTIME_KEY=VDATE_KEY
AND S378_SERVICEFLOW=1
GROUP BY S372_CALLINGPARTYNUMBER
)D ON A.MSISDN=D.S372_CALLINGPARTYNUMBER
LEFT OUTER JOIN
(SELECT /*+PARALLEL(P,15)*/ R375_CHARGINGPARTYNUMBER,SUM (R41_DEBIT_AMOUNT) RECURRING_COMBO_REVENUE 
FROM L3_RECURRING P
WHERE R377_CYCLEBEGINTIME_KEY=VDATE_KEY
AND R385_OFFERINGID IN ( SELECT OFFERING_ID FROM OFFER_DIM WHERE OFFER_TYPE='Combo')
GROUP BY R375_CHARGINGPARTYNUMBER
)E ON A.MSISDN=E.R375_CHARGINGPARTYNUMBER
LEFT OUTER JOIN
(SELECT /*+PARALLEL(P,15)*/ R375_CHARGINGPARTYNUMBER,SUM (R41_DEBIT_AMOUNT) RECURRING_VOICE_REVENUE 
FROM L3_RECURRING P
WHERE R377_CYCLEBEGINTIME_KEY=VDATE_KEY
AND R385_OFFERINGID IN ( SELECT OFFERING_ID FROM OFFER_DIM WHERE OFFER_TYPE='Voice')
GROUP BY R375_CHARGINGPARTYNUMBER
)F ON A.MSISDN=F.R375_CHARGINGPARTYNUMBER
LEFT OUTER JOIN
(SELECT /*+PARALLEL(P,15)*/ R375_CHARGINGPARTYNUMBER,SUM (R41_DEBIT_AMOUNT) RECURRING_DATA_REVENUE 
FROM L3_RECURRING P
WHERE R377_CYCLEBEGINTIME_KEY=VDATE_KEY
AND R385_OFFERINGID IN ( SELECT OFFERING_ID FROM OFFER_DIM WHERE OFFER_TYPE='Data')
GROUP BY R375_CHARGINGPARTYNUMBER
)G ON A.MSISDN=G.R375_CHARGINGPARTYNUMBER
LEFT OUTER JOIN
(SELECT /*+PARALLEL(P,15)*/ R375_CHARGINGPARTYNUMBER,SUM (R41_DEBIT_AMOUNT) RECURRING_SMS_REVENUE 
FROM L3_RECURRING P
WHERE R377_CYCLEBEGINTIME_KEY=VDATE_KEY
AND R385_OFFERINGID IN ( SELECT OFFERING_ID FROM OFFER_DIM WHERE OFFER_TYPE='SMS')
GROUP BY R375_CHARGINGPARTYNUMBER
)H ON A.MSISDN=H.R375_CHARGINGPARTYNUMBER
LEFT OUTER JOIN
(
SELECT /*+PARALLEL(P,15)*/ RE6_PRI_IDENTITY ,SUM(RE3_RECHARGE_AMT) RECHARGE_AMOUNT 
FROM L3_RECHARGE P
WHERE RE30_ENTRY_DATE_KEY = VDATE_KEY
GROUP BY RE6_PRI_IDENTITY
)I ON A.MSISDN=I.RE6_PRI_IDENTITY
;
    COMMIT;
END;
/

