--
-- P_CUSTOMER_ANALYTICS_04_MANUAL  (Procedure) 
--
CREATE OR REPLACE PROCEDURE DWH_USER.P_CUSTOMER_ANALYTICS_04_MANUAL (P_PROCESS_DATE VARCHAR2) IS
    VDATE               DATE := TO_DATE(TO_DATE(P_PROCESS_DATE,'YYYYMMDD'),'DD/MM/RRRR');
BEGIN

MERGE INTO CUSTOMER_ANALYTICS_LD A
    USING (SELECT MSISDN,MAINOFFERINGID,PRODUCT_NAME 
           FROM MSISDN_PRODUCT_WISE_LD A,PRODUCT_DIM B
           WHERE A.MAINOFFERINGID=B.PRODUCT_ID
           GROUP BY MSISDN,MAINOFFERINGID,PRODUCT_NAME)B   
    ON (A.MSISDN = B.MSISDN AND TRUNC(A.SNAPSHOT_DATE)=TRUNC(VDATE)) 
    WHEN MATCHED THEN
    UPDATE SET A.PRODUCT_NAME=B.PRODUCT_NAME;
    COMMIT; 
END;
/

