--
-- P_CUSTOMER_ANALYTICS_03  (Procedure) 
--
CREATE OR REPLACE PROCEDURE DWH_USER.P_CUSTOMER_ANALYTICS_03 IS
BEGIN

    DELETE /*parallel(A,16)*/ FROM MSISDN_PRODUCT_WISE_LD A
    WHERE ROWID>(SELECT /*parallel(B,16)*/MIN(ROWID)  FROM MSISDN_PRODUCT_WISE_LD B
    WHERE A.MSISDN=B.MSISDN);
    COMMIT;
END;
/

