--
-- P_CUSTOMER_ANALYTICS_01  (Procedure) 
--
CREATE OR REPLACE PROCEDURE DWH_USER.P_CUSTOMER_ANALYTICS_01 IS
BEGIN
    ------------------INSERT MSISDN------------------------
    EXECUTE IMMEDIATE 'TRUNCATE TABLE CUSTOMER_ANALYTICS_LD DROP STORAGE';

    INSERT INTO CUSTOMER_ANALYTICS_LD (MSISDN, FST_DAY_ON_NETWORK, SNAPSHOT_DATE, PROCESSING_DATE)
    SELECT /*+ PARALLEL(A,16) */ /*+ PARALLEL(A,8) */ SERVICE_NUMBER, 
    START_DATE AS FST_DAY_ON_NETWORK,
    SYSDATE-1 AS SNAPSHOT_DATE, 
    SYSDATE AS PROCESSING_DATE 
    FROM SUBSCRIPTION_DIM A
    WHERE A.SERVICE_NUMBER NOT IN (SELECT /*+ PARALLEL(A,16) */ MSISDN FROM CUSTOMER_ANALYTICS_LD);
    COMMIT;
END;
/

