--
-- P_CUSTOMER_ANALYTICS_08  (Procedure) 
--
CREATE OR REPLACE PROCEDURE DWH_USER.P_CUSTOMER_ANALYTICS_08 IS
BEGIN

    ----------------------LD_VOICE_DURATION----------------------------------------
    MERGE INTO CUSTOMER_ANALYTICS_LD A
    USING(SELECT /*+ PARALLEL(A,16) */ V372_CALLINGPARTYNUMBER AS MSISDN,SUM(V35_RATE_USAGE) AS LD_VOICE_DURATION                
    FROM L3_VOICE
    WHERE V387_CHARGINGTIME_KEY = (SELECT   DATE_KEY FROM DATE_DIM WHERE TRUNC(DATE_VALUE)=TRUNC(SYSDATE-1))
    GROUP BY V372_CALLINGPARTYNUMBER
    )B   
    ON (A.MSISDN = B.MSISDN) 
    WHEN MATCHED THEN
    UPDATE SET A.LD_VOICE_DURATION=B.LD_VOICE_DURATION;
    COMMIT;
END;
/

