--
-- P_CUSTOMER_ANALYTICS_23_MANUAL  (Procedure) 
--
CREATE OR REPLACE PROCEDURE DWH_USER.P_CUSTOMER_ANALYTICS_23_MANUAL (P_PROCESS_DATE VARCHAR2) IS
    VDATE_KEY           VARCHAR2(4);
    VDATE               DATE := TO_DATE(TO_DATE(P_PROCESS_DATE,'YYYYMMDD'),'DD/MM/RRRR');
BEGIN
    SELECT DATE_KEY INTO VDATE_KEY 
    FROM DATE_DIM
    WHERE DATE_KEY = (SELECT A.DATE_KEY FROM DATE_DIM A WHERE A.DATE_VALUE = VDATE);

    -------------------------------LD_VOC_CNT_AS_SCE_PRT-----------------------------
    MERGE INTO CUSTOMER_ANALYTICS_LD A
    USING(SELECT MSISDN,DISTRICT
    FROM
    (SELECT /* + parallel(A,16)*/  A.MSISDN,B.DISTRICT,ROW_NUMBER () OVER(PARTITION BY MSISDN ORDER BY B.DISTRICT)LS
    FROM LAST_ACTIVITY_FCT A, ZONE_DIM B
    WHERE A.ETL_DATE_KEY=VDATE_KEY
    AND A.LU_LOCATION_KEY=B.CGI)
    WHERE LS=1 )B   
    ON (A.MSISDN = B.MSISDN) 
    WHEN MATCHED THEN
    UPDATE SET A.LOCATION_NAME=B.DISTRICT;
    COMMIT;

END;
/

