--
-- P_CUSTOMER_ANALYTICS_06  (Procedure) 
--
CREATE OR REPLACE PROCEDURE DWH_USER.P_CUSTOMER_ANALYTICS_06 IS
BEGIN

    ------------------------LD_DATA_VOL(MB)---------------------------------
    MERGE INTO CUSTOMER_ANALYTICS_LD A
    USING(SELECT /*+ PARALLEL(A,16) */ MSISDN, TO_CHAR(LD_DATA_VOL/1048576,'FM9999999.90') AS LD_DATA_VOL
    FROM(
    SELECT /*+ PARALLEL(A,16) */ G372_CALLINGPARTYNUMBER AS MSISDN,SUM(G384_TOTALFLUX) AS LD_DATA_VOL 
    FROM L3_DATA
    WHERE G383_CHARGINGTIME_KEY = (SELECT  DATE_KEY FROM DATE_DIM WHERE TRUNC(DATE_VALUE)=TRUNC(SYSDATE-1))
    GROUP BY G372_CALLINGPARTYNUMBER
    ))B   
    ON (A.MSISDN = B.MSISDN) 
    WHEN MATCHED THEN
    UPDATE SET A.LD_DATA_VOL=B.LD_DATA_VOL;
    COMMIT;
END;
/

