--
-- P_CUSTOMER_ANALYTICS_12_MANUAL  (Procedure) 
--
CREATE OR REPLACE PROCEDURE DWH_USER.P_CUSTOMER_ANALYTICS_12_MANUAL (P_PROCESS_DATE VARCHAR2) IS
    VDATE_KEY           VARCHAR2(4);
    VDATE               DATE := TO_DATE(TO_DATE(P_PROCESS_DATE,'YYYYMMDD'),'DD/MM/RRRR');
BEGIN
    SELECT DATE_KEY INTO VDATE_KEY 
    FROM DATE_DIM
    WHERE DATE_KEY = (SELECT A.DATE_KEY FROM DATE_DIM A WHERE A.DATE_VALUE = VDATE);
    ----------------------------------------------LD_VAS_REV--------------------
    MERGE INTO CUSTOMER_ANALYTICS_LD A
    USING(SELECT C.MSISDN,SUM(C.LD_VAS_REV) AS LD_VAS_REV FROM 
    (SELECT /*+ PARALLEL(E,16) */ R375_CHARGINGPARTYNUMBER AS MSISDN,SUM(R41_DEBIT_AMOUNT) AS LD_VAS_REV
    FROM L3_RECURRING E
    WHERE R377_CYCLEBEGINTIME_KEY = VDATE_KEY
    AND R385_OFFERINGID=(SELECT OFFERING_ID FROM OFFER_DIM WHERE OFFER_TYPE='MCN')
    GROUP BY R375_CHARGINGPARTYNUMBER
    UNION
    SELECT /*+ PARALLEL (D,16) */ CO372_CALLINGPARTYNUMBER AS MSISDN, SUM(CO41_DEBIT_AMOUNT) AS LD_VAS_REV
    FROM L3_CONTENT D
    WHERE CO402_STARTTIMEOFBILLCYL_KEY = VDATE_KEY
    GROUP BY CO372_CALLINGPARTYNUMBER) C
    GROUP BY C.MSISDN)B   
    ON (A.MSISDN = B.MSISDN) 
    WHEN MATCHED THEN
    UPDATE SET A.LD_VAS_REV=B.LD_VAS_REV;
    COMMIT;
END;
/

