--
-- P_CUSTOMER_ANALYTICS_04  (Procedure) 
--
CREATE OR REPLACE PROCEDURE DWH_USER.P_CUSTOMER_ANALYTICS_04 IS
BEGIN
    MERGE INTO CUSTOMER_ANALYTICS_LD A
    USING (SELECT MSISDN,MAINOFFERINGID,PRODUCT_NAME 
           FROM MSISDN_PRODUCT_WISE_LD A,PRODUCT_DIM B
           WHERE A.MAINOFFERINGID=B.PRODUCT_ID
           group by MSISDN,MAINOFFERINGID,PRODUCT_NAME)B   
    ON (A.MSISDN = b.MSISDN AND TRUNC(A.SNAPSHOT_DATE)=TRUNC(SYSDATE-1)) 
    WHEN MATCHED THEN
    UPDATE SET A.PRODUCT_NAME=B.PRODUCT_NAME;
    COMMIT;
END;
/

