--
-- P_CUSTOMER_ANALYTICS_06_MANUAL  (Procedure) 
--
CREATE OR REPLACE PROCEDURE DWH_USER.P_CUSTOMER_ANALYTICS_06_MANUAL (P_PROCESS_DATE VARCHAR2) IS
    VDATE_KEY           VARCHAR2(4);
    VDATE               DATE := TO_DATE(TO_DATE(P_PROCESS_DATE,'YYYYMMDD'),'DD/MM/RRRR');
BEGIN
    SELECT DATE_KEY INTO VDATE_KEY 
    FROM DATE_DIM
    WHERE DATE_KEY = (SELECT A.DATE_KEY FROM DATE_DIM A WHERE A.DATE_VALUE = VDATE);
    ------------------------LD_DATA_VOL(MB)---------------------------------
    MERGE INTO CUSTOMER_ANALYTICS_LD A
    USING(SELECT /*+ PARALLEL(A,16) */ MSISDN, TO_CHAR(LD_DATA_VOL/1048576,'FM9999999.90') AS LD_DATA_VOL
    FROM(
    SELECT /*+ PARALLEL(A,16) */ G372_CALLINGPARTYNUMBER AS MSISDN,SUM(G384_TOTALFLUX) AS LD_DATA_VOL 
    FROM L3_DATA
    WHERE G383_CHARGINGTIME_KEY = VDATE_KEY
    GROUP BY G372_CALLINGPARTYNUMBER
    ))B   
    ON (A.MSISDN = B.MSISDN) 
    WHEN MATCHED THEN
    UPDATE SET A.LD_DATA_VOL=B.LD_DATA_VOL;
    COMMIT;
END;
/

