--
-- P_CUSTOMER_ANALYTICS_17_MANUAL  (Procedure) 
--
CREATE OR REPLACE PROCEDURE DWH_USER.P_CUSTOMER_ANALYTICS_17_MANUAL (P_PROCESS_DATE VARCHAR2) IS
    VDATE_KEY           VARCHAR2(4);
    VDATE               DATE := TO_DATE(TO_DATE(P_PROCESS_DATE,'YYYYMMDD'),'DD/MM/RRRR');
BEGIN
    SELECT DATE_KEY INTO VDATE_KEY 
    FROM DATE_DIM
    WHERE DATE_KEY = (SELECT A.DATE_KEY FROM DATE_DIM A WHERE A.DATE_VALUE = VDATE);
    ----------------------------LD_TOTAL_PCK_BUY_CNT--------------------------------
    MERGE INTO CUSTOMER_ANALYTICS_LD A
    USING(SELECT /*+ PARALLEL(A,16) */ R375_CHARGINGPARTYNUMBER AS MSISDN,COUNT(R375_CHARGINGPARTYNUMBER) AS LD_TOTAL_PCK_BUY_CNT
    FROM L3_RECURRING A
    WHERE R377_CYCLEBEGINTIME_KEY = VDATE_KEY
    GROUP BY R375_CHARGINGPARTYNUMBER)B   
    ON (A.MSISDN = B.MSISDN) 
    WHEN MATCHED THEN
    UPDATE SET A.LD_TOTAL_PCK_BUY_CNT=B.LD_TOTAL_PCK_BUY_CNT;
    COMMIT;
END;
/

