--
-- P_CUSTOMER_ANALYTICS_23  (Procedure) 
--
CREATE OR REPLACE PROCEDURE DWH_USER.P_CUSTOMER_ANALYTICS_23 IS

BEGIN
    -------------------------------LD_VOC_CNT_AS_SCE_PRT-----------------------------
    MERGE INTO CUSTOMER_ANALYTICS_LD A
    USING(SELECT MSISDN,DISTRICT
    FROM
    (SELECT /* + parallel(A,16)*/  A.MSISDN,B.DISTRICT,ROW_NUMBER () OVER(PARTITION BY MSISDN ORDER BY B.DISTRICT)LS
    FROM LAST_ACTIVITY_FCT_LD A, ZONE_DIM B
    WHERE A.LU_LOCATION_KEY=B.CGI)
    WHERE LS=1 )B  
    ON (A.MSISDN = B.MSISDN) 
    WHEN MATCHED THEN
    UPDATE SET A.LOCATION_NAME=B.DISTRICT;
    COMMIT;
END;
/

