--
-- P_CUSTOMER_ANALYTICS_20_MANUAL  (Procedure) 
--
CREATE OR REPLACE PROCEDURE DWH_USER.P_CUSTOMER_ANALYTICS_20_MANUAL (P_PROCESS_DATE VARCHAR2) IS
    VDATE_KEY           VARCHAR2(4);
    VDATE               DATE := TO_DATE(TO_DATE(P_PROCESS_DATE,'YYYYMMDD'),'DD/MM/RRRR');
BEGIN
    SELECT DATE_KEY INTO VDATE_KEY 
    FROM DATE_DIM
    WHERE DATE_KEY = (SELECT A.DATE_KEY FROM DATE_DIM A WHERE A.DATE_VALUE = VDATE);
    ----------------------------LD_VOC_DUR_AS_SCE_PRT--------------
    MERGE INTO CUSTOMER_ANALYTICS_LD A
    USING(SELECT /*+ PARALLEL(A,16) */ V372_CALLINGPARTYNUMBER AS MSISDN,SUM(V35_RATE_USAGE) AS LD_VOC_DUR_AS_SCE_PRT
    FROM L3_VOICE A
    WHERE V387_CHARGINGTIME_KEY =VDATE_KEY
    AND V378_SERVICEFLOW=2
    GROUP BY V372_CALLINGPARTYNUMBER
    )B   
    ON (A.MSISDN = B.MSISDN) 
    WHEN MATCHED THEN
    UPDATE SET A.LD_VOC_DUR_AS_SCE_PRT=B.LD_VOC_DUR_AS_SCE_PRT;
    COMMIT;
END;
/

