--
-- P_CUSTOMER_ANALYTICS_22  (Procedure) 
--
CREATE OR REPLACE PROCEDURE DWH_USER.P_CUSTOMER_ANALYTICS_22 IS
BEGIN
    MERGE INTO CUSTOMER_ANALYTICS_LD A
    USING (SELECT /*+ PARALLEL(M,16) */  M.msisdn,SUM(LD_TOTAL_REV) AS LD_TOTAL_REV
    FROM
    (
    SELECT /*+ PARALLEL(A,16) */ C.msisdn,COALESCE (A.VOICE_REVENUE, 0)
    + COALESCE (B.DATA_REVENUE, 0)  + COALESCE (D.VAS_REVENUE, 0) + COALESCE (E.SMS_REVENUE, 0) AS LD_TOTAL_REV
    FROM
    (SELECT /*+ PARALLEL(A,16) */ SERVICE_NUMBER as msisdn FROM SUBSCRIPTION_DIM )C
    LEFT OUTER JOIN
    (SELECT /*+ PARALLEL(A,16) */ A.V372_CALLINGPARTYNUMBER, SUM(A.V41_DEBIT_AMOUNT) VOICE_REVENUE FROM L3_VOICE A
    WHERE V387_CHARGINGTIME_KEY  = (SELECT DATE_KEY FROM DATE_DIM WHERE TRUNC(DATE_VALUE)=TRUNC(SYSDATE-1))
     AND V378_SERVICEFLOW='1'
    GROUP BY A.V372_CALLINGPARTYNUMBER) A ON   C.msisdn = A.V372_CALLINGPARTYNUMBER 
    LEFT OUTER JOIN
    (SELECT /*+ PARALLEL(A,16) */ A.G372_CALLINGPARTYNUMBER, SUM(G41_DEBIT_AMOUNT) DATA_REVENUE FROM L3_DATA A
    WHERE G383_CHARGINGTIME_KEY  = (SELECT DATE_KEY FROM DATE_DIM WHERE TRUNC(DATE_VALUE)=TRUNC(SYSDATE-1))
    GROUP BY A.G372_CALLINGPARTYNUMBER )B ON C.msisdn = B.G372_CALLINGPARTYNUMBER
    LEFT OUTER JOIN
    (SELECT /*+ PARALLEL(A,16) */ R375_CHARGINGPARTYNUMBER,SUM(R41_DEBIT_AMOUNT) VAS_REVENUE FROM L3_RECURRING A
    WHERE R377_CYCLEBEGINTIME_KEY  = (SELECT DATE_KEY FROM DATE_DIM WHERE TRUNC(DATE_VALUE)=TRUNC(SYSDATE-1))
    GROUP BY R375_CHARGINGPARTYNUMBER)D ON C.msisdn = D.R375_CHARGINGPARTYNUMBER  
    LEFT OUTER JOIN
    (SELECT /*+ PARALLEL(A,16) */ S22_PRI_IDENTITY,SUM(S41_DEBIT_AMOUNT) SMS_REVENUE FROM L3_SMS A
    WHERE S387_CHARGINGTIME_KEY  = (SELECT DATE_KEY FROM DATE_DIM WHERE TRUNC(DATE_VALUE)=TRUNC(SYSDATE-1))
    AND S378_SERVICEFLOW='1'
    GROUP BY S22_PRI_IDENTITY )E ON C.msisdn = E.S22_PRI_IDENTITY
    )M
    group by M.msisdn) b
    ON (A.MSISDN = B.MSISDN) 
    WHEN MATCHED THEN
    UPDATE SET A.LD_TOTAL_REV=B.LD_TOTAL_REV;
    COMMIT;
end;
/

