--
-- P_CUSTOMER_ANALYTICS_10  (Procedure) 
--
CREATE OR REPLACE PROCEDURE DWH_USER.P_CUSTOMER_ANALYTICS_10 IS
BEGIN

    -----------------------------------LD_SMS_CNT-----------------
    MERGE INTO CUSTOMER_ANALYTICS_LD A
    USING(SELECT /*+ PARALLEL(A,16) */ S22_PRI_IDENTITY AS MSISDN,COUNT(S22_PRI_IDENTITY) AS LD_SMS_CNT
    FROM L3_SMS
    WHERE S387_CHARGINGTIME_KEY = (SELECT   DATE_KEY FROM DATE_DIM WHERE TRUNC(DATE_VALUE)=TRUNC(SYSDATE-1))
    AND S378_SERVICEFLOW=1
    GROUP BY S22_PRI_IDENTITY)B   
    ON (A.MSISDN = B.MSISDN) 
    WHEN MATCHED THEN
    UPDATE SET A.LD_SMS_CNT=B.LD_SMS_CNT;
    COMMIT;
END;
/

