--
-- P_CUSTOMER_ANALYTICS_05  (Procedure) 
--
CREATE OR REPLACE PROCEDURE DWH_USER.P_CUSTOMER_ANALYTICS_05 IS
BEGIN

    ------------------RECHARGE AMOUNT SUM ------------------------
    MERGE INTO CUSTOMER_ANALYTICS_LD A
    USING(SELECT /*+ PARALLEL(A,16) */ RE6_PRI_IDENTITY AS MSISDN, SUM(RE3_RECHARGE_AMT) AS RE3_RECHARGE_AMT
    FROM L3_RECHARGE
    WHERE RE30_ENTRY_DATE_KEY=(SELECT DATE_KEY FROM DATE_DIM WHERE TRUNC(DATE_VALUE) = TRUNC(SYSDATE-1))
    GROUP BY RE6_PRI_IDENTITY
    )B   
    ON (A.MSISDN = B.MSISDN) 
    WHEN MATCHED THEN
    UPDATE SET A.LD_RECHARGE=B.RE3_RECHARGE_AMT;
    COMMIT;
END;
/

