--
-- P_CUSTOMER_ANALYTICS_22_MANUAL  (Procedure) 
--
CREATE OR REPLACE PROCEDURE DWH_USER.P_CUSTOMER_ANALYTICS_22_MANUAL (P_PROCESS_DATE VARCHAR2) IS
    VDATE_KEY           VARCHAR2(4);
    VDATE               DATE := TO_DATE(TO_DATE(P_PROCESS_DATE,'YYYYMMDD'),'DD/MM/RRRR');
BEGIN
    SELECT DATE_KEY INTO VDATE_KEY 
    FROM DATE_DIM
    WHERE DATE_KEY = (SELECT A.DATE_KEY FROM DATE_DIM A WHERE A.DATE_VALUE = VDATE);
    
    MERGE INTO CUSTOMER_ANALYTICS_LD A
    USING (select msisdn,sum(LD_TOTAL_REV)as LD_TOTAL_REV
    from
    (SELECT /*+ PARALLEL(A,16) */ C.msisdn,COALESCE (A.VOICE_REVENUE, 0)
    + COALESCE (B.DATA_REVENUE, 0)  + COALESCE (D.VAS_REVENUE, 0) + COALESCE (E.SMS_REVENUE, 0) AS LD_TOTAL_REV
    FROM
    (SELECT /*+ PARALLEL(A,16) */ SERVICE_NUMBER as msisdn FROM SUBSCRIPTION_DIM )C
    LEFT OUTER JOIN
    (SELECT /*+ PARALLEL(A,16) */ A.V372_CALLINGPARTYNUMBER, SUM(A.V41_DEBIT_AMOUNT) VOICE_REVENUE FROM L3_VOICE A
    WHERE V387_CHARGINGTIME_KEY  = VDATE_KEY
     AND V378_SERVICEFLOW='1'
    GROUP BY A.V372_CALLINGPARTYNUMBER) A ON   C.msisdn = A.V372_CALLINGPARTYNUMBER 
    LEFT OUTER JOIN
    (SELECT /*+ PARALLEL(A,16) */ A.G372_CALLINGPARTYNUMBER, SUM(G41_DEBIT_AMOUNT) DATA_REVENUE FROM L3_DATA A
    WHERE G383_CHARGINGTIME_KEY  = VDATE_KEY
    GROUP BY A.G372_CALLINGPARTYNUMBER )B ON C.msisdn = B.G372_CALLINGPARTYNUMBER
    LEFT OUTER JOIN
    (SELECT /*+ PARALLEL(A,16) */ R375_CHARGINGPARTYNUMBER,SUM(R41_DEBIT_AMOUNT) VAS_REVENUE FROM L3_RECURRING A
    WHERE R377_CYCLEBEGINTIME_KEY  = VDATE_KEY
    GROUP BY R375_CHARGINGPARTYNUMBER)D ON C.msisdn = D.R375_CHARGINGPARTYNUMBER  
    LEFT OUTER JOIN
    (SELECT /*+ PARALLEL(A,16) */ S22_PRI_IDENTITY,SUM(S41_DEBIT_AMOUNT) SMS_REVENUE FROM L3_SMS A
    WHERE S387_CHARGINGTIME_KEY  = VDATE_KEY
    AND S378_SERVICEFLOW='1'
    GROUP BY S22_PRI_IDENTITY )E ON C.msisdn = E.S22_PRI_IDENTITY) 
    group by msisdn)b
    ON (A.MSISDN = B.MSISDN) 
    WHEN MATCHED THEN
    UPDATE SET A.LD_TOTAL_REV=B.LD_TOTAL_REV;
    COMMIT;
end;
/

